// pages/Legal/Terms.jsx
import { ArrowLeft, FileText } from "lucide-react";
import { useNavigate } from "react-router-dom";

const GOLD   = "#D4A856";
const TEXT   = "#F0E6D2";
const MUTED  = "rgba(180,195,230,0.5)";
const PANEL  = "rgba(20,17,12,0.7)";
const BORDER = "rgba(212,168,86,0.15)";

const Section = ({ title, children }) => (
  <div className="flex flex-col gap-2">
    <h2 className="text-sm font-semibold" style={{ color: GOLD }}>
      {title}
    </h2>
    <p className="text-sm leading-relaxed" style={{ color: MUTED }}>
      {children}
    </p>
  </div>
);

const TermsPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen" style={{ background: "#0A0908" }}>
      {/* Top bar */}
      <div
        className="sticky top-0 z-10 flex items-center gap-4 px-6 py-4"
        style={{
          background: "rgba(10,9,8,0.92)",
          borderBottom: `1px solid ${BORDER}`,
          backdropFilter: "blur(12px)",
        }}
      >
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-1.5 text-sm transition-all cursor-pointer hover:opacity-80"
          style={{ color: MUTED }}
        >
          <ArrowLeft size={15} />
          Back
        </button>
        <div className="h-4 w-px" style={{ background: BORDER }} />
        <div className="flex items-center gap-2">
          <FileText size={14} style={{ color: GOLD }} />
          <span className="text-sm font-medium" style={{ color: TEXT }}>
            Terms &amp; Conditions
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-10">
        <div
          className="rounded-3xl p-8 flex flex-col gap-6"
          style={{ background: PANEL, border: `1px solid ${BORDER}` }}
        >
          <div className="flex flex-col gap-1">
            <h1 className="text-xl font-bold" style={{ color: TEXT }}>
              Terms &amp; Conditions
            </h1>
            <p className="text-xs" style={{ color: MUTED }}>
              Last updated: June 2026
            </p>
          </div>

          <div
            className="h-px w-full"
            style={{ background: BORDER }}
          />

          <Section title="1. Acceptance of Terms">
            By accessing or using StudyMind AI, you agree to be bound by these terms. If you
            do not agree, please discontinue use immediately. These terms apply to all users
            of the platform.
          </Section>

          <Section title="2. Use of the Service">
            StudyMind AI is an AI-powered study companion intended for educational use. You
            agree to use it only for lawful, personal academic purposes. You may not attempt
            to reverse-engineer, scrape, or abuse the platform in any way.
          </Section>

          <Section title="3. User Content">
            You retain ownership of all documents and content you upload. By uploading
            content, you grant StudyMind AI a limited licence to process it solely for
            generating study materials on your behalf. We do not share your content with
            third parties.
          </Section>

          <Section title="4. AI-Generated Content">
            All quizzes, study plans, and chat responses are generated by AI and may contain
            inaccuracies. StudyMind AI does not guarantee the correctness of any generated
            content. Always cross-reference with authoritative sources before relying on it
            for academic assessment.
          </Section>

          <Section title="5. Account Security">
            You are responsible for maintaining the confidentiality of your credentials. Any
            activity under your account is your responsibility. Notify us immediately if you
            suspect unauthorised access.
          </Section>

          <Section title="6. Intellectual Property">
            The StudyMind AI platform, interface, and underlying code are the intellectual
            property of the developer. You may not copy, reproduce, or distribute any part
            of the platform without explicit written permission.
          </Section>

          <Section title="7. Limitation of Liability">
            StudyMind AI is provided as-is, without warranties of any kind. The developer
            shall not be liable for any academic outcomes, data loss, or indirect damages
            arising from use of the platform.
          </Section>

          <Section title="8. Changes to Terms">
            These terms may be updated at any time. Continued use of the platform after
            changes constitutes acceptance of the revised terms.
          </Section>

          <Section title="9. Contact">
            For questions regarding these terms, contact the developer at
            abhikkundu09@gmail.com.
          </Section>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;